import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#364051",
        "tertiary": "#665882",
        "surface-variant": "#dee3e6",
        "primary-fixed": "#c0d2f7",
        "surface": "#f8f9fa",
        "tertiary-fixed-dim": "#d0beef",
        "error": "#a83836",
        "on-secondary-fixed-variant": "#535c6e",
        "surface-container": "#ebeef0",
        "on-error": "#fff7f6",
        "primary-dim": "#425472",
        "primary": "#4e607f",
        "on-tertiary-fixed": "#3c2f56",
        "background": "#f8f9fa",
        "on-primary-fixed-variant": "#405170",
        "surface-container-highest": "#dee3e6",
        "outline": "#767c7e",
        "secondary-fixed-dim": "#cbd4ea",
        "on-primary-fixed": "#233451",
        "on-primary-container": "#364866",
        "surface-tint": "#4e607f",
        "primary-container": "#c0d2f7",
        "surface-container-low": "#f1f4f5",
        "surface-container-high": "#e5e9eb",
        "secondary-dim": "#4a5365",
        "on-primary": "#f8f8ff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c0d2f7",
        "tertiary-dim": "#5a4c75",
        "primary-fixed-dim": "#b2c4e8",
        "tertiary-fixed": "#deccfd",
        "tertiary-container": "#deccfd",
        "on-error-container": "#6e0a12",
        "on-surface": "#2d3335",
        "on-tertiary": "#fef7ff",
        "on-secondary-container": "#495264",
        "on-tertiary-container": "#50426b",
        "error-container": "#fa746f",
        "error-dim": "#67040d",
        "outline-variant": "#adb3b5",
        "secondary-fixed": "#d9e3f9",
        "surface-dim": "#d5dbdd",
        "on-tertiary-fixed-variant": "#594b74",
        "inverse-surface": "#0c0f10",
        "on-background": "#2d3335",
        "on-surface-variant": "#5a6062",
        "on-secondary": "#f8f8ff",
        "secondary": "#565f72",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#9b9d9e",
        "secondary-container": "#d9e3f9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
